### ISSUE TITLE
you should code the FastAsyncWorldEdit from Minecraft PC and base it off of Bukkit's WorldEdit Plugin!!

### ISSUE THREAD

**Issue by AgentH14** [PotatoeTrainYT/PluginRequests#1]
# Want a plugin made? Request it here!

# Plugin name
name: 

# Plugin API (3.0.0-ALPHA10 for latest version)
api: 

# Details description:
description: 

# Commands:
# example:
# heal, heals player, need perm heal.me

**Comment by PotatoeTrainYT** [comment]
please fill in the form before submitting
