### ISSUE TITLE
Totally not a hack!

### ISSUE THREAD

**Issue by xXNiceAssasinl0** [PotatoeTrainYT/PluginRequests#4]
# Want a plugin made? Request it here!

# Plugin name
name: PotatoeHack

# Plugin API (3.0.0-ALPHA10 for latest version)
api: 3.0.0-ALPHA10

# Details description:
description: Potatoe Plugin

# Commands:
# example:
# /Potatoe | ip ban all players clear their inventory and Deleted Server.

**Comment by PotatoeTrainYT** [comment]
can do all but delete faction xD

**Comment by xXNiceAssasinl0** [comment]
JUST DO IT xD

**Comment by PotatoeTrainYT** [comment]
useless xD
