### ISSUE TITLE
FastAsyncWorldEdit 

### ISSUE THREAD

**Issue by AgentH14** [PotatoeTrainYT/PluginRequests#5]
# Want a plugin made? Request it here!

# Plugin name
name: 
FastAsyncWorldEdit
# Plugin API (3.0.0-ALPHA10 for latest version)
api: 
3.0.0-ALPHA10
# Details description:
description: 
FastAsyncWorldEdit from the Minecraft PC WorldEdit Bukkit plugin
# Commands:
//stack, //move, //expand, //flip, etc..
# example:

**Comment by PotatoeTrainYT** [comment]
why dont u request this on [MagicWE2](https://github.com/thebigsmileXD/MagicWE2) xD
